# Generated by Django 2.2.18 on 2021-02-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Check_in',
            new_name='Check_In',
        ),
    ]
