# Generated by Django 2.2.18 on 2021-02-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0003_auto_20210213_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='Check_Out',
            new_name='Check_out',
        ),
    ]
