# Generated by Django 2.2.18 on 2021-02-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudApp', '0004_auto_20210213_0239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='personass',
        ),
    ]
